Dado que el entrenamiento de redes neuronales es una tarea  muy costosa, **se recomienda ejecutar el notebooks en [Google Colab](https://colab.research.google.com)**, por supuesto también se puede ejecutar en local.

Al entrar en [Google Colab](https://colab.research.google.com) bastará con hacer click en `upload` y subir este notebook. No olvide luego descargarlo en `File->Download .ipynb`

**El examen deberá ser entregado con las celdas ejecutadas, si alguna celda no está ejecutadas no se contará.**

El examen se divide en preguntas de código y preguntas teóricas, con la puntuación que se indica a continuación. La puntuación máxima será 10.

- [Actividad 1: Redes Densas](#actividad_1): 10 pts
    - Correcta normalización: máximo de 0.5 pts
    - [Cuestión 1](#1.1): 1.5 pts
    - [Cuestión 2](#1.2): 1.5 pts
    - [Cuestión 3](#1.3): 1.5 pts
    - [Cuestión 4](#1.4): 1 pts
    - [Cuestión 5](#1.5): 1 pts
    - [Cuestión 6](#1.6): 1 pts
    - [Cuestión 7](#1.7): 1 pts
    - [Cuestión 8](#1.8): 1 pts

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

<a name='actividad_1'></a>
# Actividad 1: Redes Densas

Para esta actividad vamos a utilizar el [wine quality dataset](https://archive.ics.uci.edu/ml/datasets/wine+quality). Con el que trataremos de predecir la calidad del vino.

La calidad del vino puede tomar valores decimales (por ejemplo 7.25), independientemente de que en el dataset de entrenamiento sean números enteros. Por lo tanto, el problema es una `regresión`.

**Puntuación**:

Normalizar las features correctamente (x_train, x_test): 0.5 pts

- Correcta normalización: máximo de 0.5 pts
- [Cuestión 1](#1.1): 1 pt
- [Cuestión 2](#1.2): 1 pt
- [Cuestión 3](#1.3): 0.5 pts
- [Cuestión 4](#1.4): 0.5 pts
- [Cuestión 5](#1.5): 0.5 pts
- [Cuestión 6](#1.6): 0.5 pts
- [Cuestión 7](#1.7): 0.5 pts
- [Cuestión 8](#1.8): 0.5 pts

In [2]:
# Descargar los datos con pandas
df_red = pd.read_csv(
    'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',
    sep=';'
)
df_white = pd.read_csv(
    'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv',
    sep=';'
)
df = pd.concat([df_red, df_white])

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
df['quality'].agg(['min','max'])

min    3
max    9
Name: quality, dtype: int64

In [4]:
feature_names = [
    'fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides',
    'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol'
]


# separar features y target
y = df.pop('quality').values
X = df.copy().values

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

print('x_train, y_train shapes:', x_train.shape, y_train.shape)
print('x_test, y_test shapes:', x_test.shape, y_test.shape)
print('Some qualities: ', y_train[:5])

x_train, y_train shapes: (4872, 11) (4872,)
x_test, y_test shapes: (1625, 11) (1625,)
Some qualities:  [6 7 8 5 6]

In [ ]:
## Si quiere, puede normalizar las features

In [6]:

from sklearn.preprocessing import StandardScaler



x_scaler = StandardScaler()
x_scaler.fit(x_train)
x_train_scaled = x_scaler.transform(x_train).astype(np.float32)
x_test_scaled  = x_scaler.transform(x_test).astype(np.float32)


print(x_train_scaled.mean(axis=0)[:3], x_train_scaled.std(axis=0)[:3])

[-1.2160718e-08 -1.4411796e-08 -6.0020604e-08] [1.0000017 1.0000048 1.0000017]

<a name='1.1'></a>
## Cuestión 1: Cree un modelo secuencial que contenga 4 capas ocultas(hidden layers), con más de 60 neuronas  por capa, sin regularización y obtenga los resultados.

Puntuación:
- Obtener el modelo correcto: 0.8 pts
- Compilar el modelo: 0.1pts
- Acertar con la función de pérdida: 0.1 pts

In [7]:
n_features = x_train_scaled.shape[1]

In [8]:

model = tf.keras.models.Sequential([
    layers.Input(shape=(n_features,)),
    layers.Dense(64, activation="relu"),   # >60
    layers.Dense(64, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(1)                        # regression：a linear output with no activation
])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,313 (52.00 KB)

 Trainable params: 13,313 (52.00 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
# Compilación del modelo

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss="mae",          # or "mse"
    metrics=["mae"]
)

In [10]:
# No modifique el código
model.fit(x_train,
          y_train,
          epochs=200,
          batch_size=32,
          validation_split=0.2,
          verbose=1)

Epoch 1/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 1.5209 - mae: 1.5209 - val_loss: 0.8345 - val_mae: 0.8345
Epoch 2/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7208 - mae: 0.7208 - val_loss: 0.9768 - val_mae: 0.9768
Epoch 3/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7453 - mae: 0.7453 - val_loss: 0.9707 - val_mae: 0.9707
Epoch 4/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7032 - mae: 0.7032 - val_loss: 0.9149 - val_mae: 0.9149
Epoch 5/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6390 - mae: 0.6390 - val_loss: 0.6359 - val_mae: 0.6359
Epoch 6/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6333 - mae: 0.6333 - val_loss: 0.5978 - val_mae: 0.5978
Epoch 7/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.6274 - mae: 0.6274 - val_loss: 0.6036 - val_mae: 0.6036
Epoch 8/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.6091 - mae: 0.6091 - val_loss: 0.5981 - val_mae: 0.5981
Epoch 9/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.6590 - mae: 0.6590 - val_loss: 0.6530 - val_mae: 0.6530
Epoch 10/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6207 - mae: 0.6207 - val_loss: 0.6148 - val_mae: 0.6148
Epoch 11/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6227 - mae: 0.6227 - val_loss: 0.6123 - val_mae: 0.6123
Epoch 12/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6094 - mae: 0.6094 - val_loss: 0.6094 - val_mae: 0.6094
Epoch 13/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6080 - mae: 0.6080 - val_loss: 0.6939 - val_mae: 0.6939
Epoch 14/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6348 - mae: 0.6348 - val_loss: 0.6145 - val_mae: 0.6145
Epoch 15/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5874 - mae: 0.5874 - val_loss: 0.5896 - val_mae: 0.5896
Epoch 16/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5835 - mae: 0.5835 - val_loss: 0.5992 - val_mae: 0.5992
Epoch 17/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5783 - mae: 0.5783 - val_loss: 0.6091 - val_mae: 0.6091
Epoch 18/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6038 - mae: 0.6038 - val_loss: 0.6113 - val_mae: 0.6113
Epoch 19/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6225 - mae: 0.6225 - val_loss: 0.6071 - val_mae: 0.6071
Epoch 20/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6409 - mae: 0.6409 - val_loss: 0.6648 - val_mae: 0.6648
Epoch 21/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6000 - mae: 0.6000 - val_loss: 0.6323 - val_mae: 0.6323
Epoch 22/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5856 - mae: 0.5856 - val_loss: 0.6087 - val_mae: 0.6087
Epoch 23/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5855 - mae: 0.5855 - val_loss: 0.5906 - val_mae: 0.5906
Epoch 24/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6142 - mae: 0.6142 - val_loss: 0.5730 - val_mae: 0.5730
Epoch 25/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5986 - mae: 0.5986 - val_loss: 0.6734 - val_mae: 0.6734
Epoch 26/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6204 - mae: 0.6204 - val_loss: 0.6421 - val_mae: 0.6421
Epoch 27/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6027 - mae: 0.6027 - val_loss: 0.5842 - val_mae: 0.5842
Epoch 28/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5907 - mae: 0.5907 - val_loss: 0.6091 - val_mae: 0.6091
Epoch 29/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5940 - mae: 0.5940 - val_loss: 0.6817 - val_mae: 0.6817
Epoch 30/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5923 - mae: 0.5923 - val_loss: 0.6052 - val_mae: 0.6052
Epoch 31/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5857 - mae: 0.5857 - val_loss: 0.5717 - val_mae: 0.5717
Epoch 32/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6030 - mae: 0.6030 - val_loss: 0.5908 - val_mae: 0.5908
Epoch 33/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5860 - mae: 0.5860 - val_loss: 0.5745 - val_mae: 0.5745
Epoch 34/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5813 - mae: 0.5813 - val_loss: 0.5822 - val_mae: 0.5822
Epoch 35/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5983 - mae: 0.5983 - val_loss: 0.5691 - val_mae: 0.5691
Epoch 36/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5658 - mae: 0.5658 - val_loss: 0.5660 - val_mae: 0.5660
Epoch 37/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.6017 - mae: 0.6017 - val_loss: 0.6659 - val_mae: 0.6659
Epoch 38/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6334 - mae: 0.6334 - val_loss: 0.5867 - val_mae: 0.5867
Epoch 39/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5686 - mae: 0.5686 - val_loss: 0.6611 - val_mae: 0.6611
Epoch 40/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5722 - mae: 0.5722 - val_loss: 0.5928 - val_mae: 0.5928
Epoch 41/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5645 - mae: 0.5645 - val_loss: 0.5882 - val_mae: 0.5882
Epoch 42/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5696 - mae: 0.5696 - val_loss: 0.5695 - val_mae: 0.5695
Epoch 43/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5768 - mae: 0.5768 - val_loss: 0.6017 - val_mae: 0.6017
Epoch 44/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5639 - mae: 0.5639 - val_loss: 0.5786 - val_mae: 0.5786
Epoch 45/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5799 - mae: 0.5799 - val_loss: 0.5704 - val_mae: 0.5704
Epoch 46/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5709 - mae: 0.5709 - val_loss: 0.5869 - val_mae: 0.5869
Epoch 47/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5988 - mae: 0.5988 - val_loss: 0.6568 - val_mae: 0.6568
Epoch 48/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5775 - mae: 0.5775 - val_loss: 0.5845 - val_mae: 0.5845
Epoch 49/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5875 - mae: 0.5875 - val_loss: 0.5706 - val_mae: 0.5706
Epoch 50/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5865 - mae: 0.5865 - val_loss: 0.6817 - val_mae: 0.6817
Epoch 51/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5957 - mae: 0.5957 - val_loss: 0.6024 - val_mae: 0.6024
Epoch 52/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5842 - mae: 0.5842 - val_loss: 0.5635 - val_mae: 0.5635
Epoch 53/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5677 - mae: 0.5677 - val_loss: 0.5608 - val_mae: 0.5608
Epoch 54/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5656 - mae: 0.5656 - val_loss: 0.5758 - val_mae: 0.5758
Epoch 55/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5810 - mae: 0.5810 - val_loss: 0.6038 - val_mae: 0.6038
Epoch 56/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5627 - mae: 0.5627 - val_loss: 0.5821 - val_mae: 0.5821
Epoch 57/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5805 - mae: 0.5805 - val_loss: 0.5663 - val_mae: 0.5663
Epoch 58/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5794 - mae: 0.5794 - val_loss: 0.5709 - val_mae: 0.5709
Epoch 59/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5795 - mae: 0.5795 - val_loss: 0.5903 - val_mae: 0.5903
Epoch 60/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5742 - mae: 0.5742 - val_loss: 0.5939 - val_mae: 0.5939
Epoch 61/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5808 - mae: 0.5808 - val_loss: 0.5653 - val_mae: 0.5653
Epoch 62/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5742 - mae: 0.5742 - val_loss: 0.5897 - val_mae: 0.5897
Epoch 63/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5477 - mae: 0.5477 - val_loss: 0.6563 - val_mae: 0.6563
Epoch 64/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.6074 - mae: 0.6074 - val_loss: 0.5816 - val_mae: 0.5816
Epoch 65/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5719 - mae: 0.5719 - val_loss: 0.5629 - val_mae: 0.5629
Epoch 66/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5669 - mae: 0.5669 - val_loss: 0.5814 - val_mae: 0.5814
Epoch 67/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5730 - mae: 0.5730 - val_loss: 0.5732 - val_mae: 0.5732
Epoch 68/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5726 - mae: 0.5726 - val_loss: 0.5995 - val_mae: 0.5995
Epoch 69/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5628 - mae: 0.5628 - val_loss: 0.5665 - val_mae: 0.5665
Epoch 70/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5481 - mae: 0.5481 - val_loss: 0.5776 - val_mae: 0.5776
Epoch 71/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5794 - mae: 0.5794 - val_loss: 0.5978 - val_mae: 0.5978
Epoch 72/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5736 - mae: 0.5736 - val_loss: 0.5826 - val_mae: 0.5826
Epoch 73/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5705 - mae: 0.5705 - val_loss: 0.5654 - val_mae: 0.5654
Epoch 74/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5604 - mae: 0.5604 - val_loss: 0.5810 - val_mae: 0.5810
Epoch 75/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5599 - mae: 0.5599 - val_loss: 0.5787 - val_mae: 0.5787
Epoch 76/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5557 - mae: 0.5557 - val_loss: 0.6053 - val_mae: 0.6053
Epoch 77/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5843 - mae: 0.5843 - val_loss: 0.5623 - val_mae: 0.5623
Epoch 78/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5794 - mae: 0.5794 - val_loss: 0.5969 - val_mae: 0.5969
Epoch 79/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5735 - mae: 0.5735 - val_loss: 0.5598 - val_mae: 0.5598
Epoch 80/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5630 - mae: 0.5630 - val_loss: 0.5577 - val_mae: 0.5577
Epoch 81/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5600 - mae: 0.5600 - val_loss: 0.5828 - val_mae: 0.5828
Epoch 82/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5647 - mae: 0.5647 - val_loss: 0.5929 - val_mae: 0.5929
Epoch 83/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5736 - mae: 0.5736 - val_loss: 0.6068 - val_mae: 0.6068
Epoch 84/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5608 - mae: 0.5608 - val_loss: 0.5741 - val_mae: 0.5741
Epoch 85/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5648 - mae: 0.5648 - val_loss: 0.5637 - val_mae: 0.5637
Epoch 86/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5644 - mae: 0.5644 - val_loss: 0.5625 - val_mae: 0.5625
Epoch 87/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5705 - mae: 0.5705 - val_loss: 0.6252 - val_mae: 0.6252
Epoch 88/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5681 - mae: 0.5681 - val_loss: 0.5597 - val_mae: 0.5597
Epoch 89/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5618 - mae: 0.5618 - val_loss: 0.5738 - val_mae: 0.5738
Epoch 90/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5811 - mae: 0.5811 - val_loss: 0.6255 - val_mae: 0.6255
Epoch 91/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.6010 - mae: 0.6010 - val_loss: 0.5560 - val_mae: 0.5560
Epoch 92/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.5659 - mae: 0.5659 - val_loss: 0.5652 - val_mae: 0.5652
Epoch 93/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.5659 - mae: 0.5659 - val_loss: 0.5730 - val_mae: 0.5730
Epoch 94/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.5625 - mae: 0.5625 - val_loss: 0.6214 - val_mae: 0.6214
Epoch 95/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5904 - mae: 0.5904 - val_loss: 0.6140 - val_mae: 0.6140
Epoch 96/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.5638 - mae: 0.5638 - val_loss: 0.5797 - val_mae: 0.5797
Epoch 97/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.5544 - mae: 0.5544 - val_loss: 0.5607 - val_mae: 0.5607
Epoch 98/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.5409 - mae: 0.5409 - val_loss: 0.5656 - val_mae: 0.5656
Epoch 99/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.5659 - mae: 0.5659 - val_loss: 0.5905 - val_mae: 0.5905
Epoch 100/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5789 - mae: 0.5789 - val_loss: 0.5626 - val_mae: 0.5626
Epoch 101/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5550 - mae: 0.5550 - val_loss: 0.5609 - val_mae: 0.5609
Epoch 102/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5419 - mae: 0.5419 - val_loss: 0.5896 - val_mae: 0.5896
Epoch 103/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5581 - mae: 0.5581 - val_loss: 0.5704 - val_mae: 0.5704
Epoch 104/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5613 - mae: 0.5613 - val_loss: 0.5693 - val_mae: 0.5693
Epoch 105/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5603 - mae: 0.5603 - val_loss: 0.5780 - val_mae: 0.5780
Epoch 106/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5633 - mae: 0.5633 - val_loss: 0.5614 - val_mae: 0.5614
Epoch 107/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5522 - mae: 0.5522 - val_loss: 0.5895 - val_mae: 0.5895
Epoch 108/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5577 - mae: 0.5577 - val_loss: 0.5533 - val_mae: 0.5533
Epoch 109/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5542 - mae: 0.5542 - val_loss: 0.6067 - val_mae: 0.6067
Epoch 110/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5839 - mae: 0.5839 - val_loss: 0.5584 - val_mae: 0.5584
Epoch 111/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5463 - mae: 0.5463 - val_loss: 0.5720 - val_mae: 0.5720
Epoch 112/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5591 - mae: 0.5591 - val_loss: 0.5782 - val_mae: 0.5782
Epoch 113/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5577 - mae: 0.5577 - val_loss: 0.5794 - val_mae: 0.5794
Epoch 114/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5900 - mae: 0.5900 - val_loss: 0.5735 - val_mae: 0.5735
Epoch 115/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5725 - mae: 0.5725 - val_loss: 0.5572 - val_mae: 0.5572
Epoch 116/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5612 - mae: 0.5612 - val_loss: 0.6184 - val_mae: 0.6184
Epoch 117/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5827 - mae: 0.5827 - val_loss: 0.5566 - val_mae: 0.5566
Epoch 118/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5738 - mae: 0.5738 - val_loss: 0.5627 - val_mae: 0.5627
Epoch 119/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5623 - mae: 0.5623 - val_loss: 0.5669 - val_mae: 0.5669
Epoch 120/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5516 - mae: 0.5516 - val_loss: 0.5815 - val_mae: 0.5815
Epoch 121/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5768 - mae: 0.5768 - val_loss: 0.5531 - val_mae: 0.5531
Epoch 122/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5426 - mae: 0.5426 - val_loss: 0.5827 - val_mae: 0.5827
Epoch 123/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5672 - mae: 0.5672 - val_loss: 0.5743 - val_mae: 0.5743
Epoch 124/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5589 - mae: 0.5589 - val_loss: 0.5897 - val_mae: 0.5897
Epoch 125/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5676 - mae: 0.5676 - val_loss: 0.5691 - val_mae: 0.5691
Epoch 126/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5481 - mae: 0.5481 - val_loss: 0.5589 - val_mae: 0.5589
Epoch 127/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5433 - mae: 0.5433 - val_loss: 0.5711 - val_mae: 0.5711
Epoch 128/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5677 - mae: 0.5677 - val_loss: 0.5813 - val_mae: 0.5813
Epoch 129/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5714 - mae: 0.5714 - val_loss: 0.5925 - val_mae: 0.5925
Epoch 130/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5669 - mae: 0.5669 - val_loss: 0.5708 - val_mae: 0.5708
Epoch 131/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5527 - mae: 0.5527 - val_loss: 0.5681 - val_mae: 0.5681
Epoch 132/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5496 - mae: 0.5496 - val_loss: 0.5578 - val_mae: 0.5578
Epoch 133/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5373 - mae: 0.5373 - val_loss: 0.5578 - val_mae: 0.5578
Epoch 134/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5819 - mae: 0.5819 - val_loss: 0.5893 - val_mae: 0.5893
Epoch 135/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5669 - mae: 0.5669 - val_loss: 0.5546 - val_mae: 0.5546
Epoch 136/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5729 - mae: 0.5729 - val_loss: 0.5605 - val_mae: 0.5605
Epoch 137/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5442 - mae: 0.5442 - val_loss: 0.5652 - val_mae: 0.5652
Epoch 138/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5679 - mae: 0.5679 - val_loss: 0.5626 - val_mae: 0.5626
Epoch 139/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5394 - mae: 0.5394 - val_loss: 0.5923 - val_mae: 0.5923
Epoch 140/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5719 - mae: 0.5719 - val_loss: 0.5748 - val_mae: 0.5748
Epoch 141/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5521 - mae: 0.5521 - val_loss: 0.5639 - val_mae: 0.5639
Epoch 142/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5449 - mae: 0.5449 - val_loss: 0.5637 - val_mae: 0.5637
Epoch 143/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5563 - mae: 0.5563 - val_loss: 0.5738 - val_mae: 0.5738
Epoch 144/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5508 - mae: 0.5508 - val_loss: 0.5661 - val_mae: 0.5661
Epoch 145/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5492 - mae: 0.5492 - val_loss: 0.5798 - val_mae: 0.5798
Epoch 146/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5440 - mae: 0.5440 - val_loss: 0.5731 - val_mae: 0.5731
Epoch 147/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5461 - mae: 0.5461 - val_loss: 0.5729 - val_mae: 0.5729
Epoch 148/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5433 - mae: 0.5433 - val_loss: 0.5563 - val_mae: 0.5563
Epoch 149/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5710 - mae: 0.5710 - val_loss: 0.5565 - val_mae: 0.5565
Epoch 150/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5454 - mae: 0.5454 - val_loss: 0.6033 - val_mae: 0.6033
Epoch 151/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5537 - mae: 0.5537 - val_loss: 0.5561 - val_mae: 0.5561
Epoch 152/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5543 - mae: 0.5543 - val_loss: 0.5589 - val_mae: 0.5589
Epoch 153/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5331 - mae: 0.5331 - val_loss: 0.5614 - val_mae: 0.5614
Epoch 154/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5517 - mae: 0.5517 - val_loss: 0.5633 - val_mae: 0.5633
Epoch 155/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5462 - mae: 0.5462 - val_loss: 0.5807 - val_mae: 0.5807
Epoch 156/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.5688 - mae: 0.5688 - val_loss: 0.5617 - val_mae: 0.5617
Epoch 157/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5592 - mae: 0.5592 - val_loss: 0.5611 - val_mae: 0.5611
Epoch 158/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5587 - mae: 0.5587 - val_loss: 0.5544 - val_mae: 0.5544
Epoch 159/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5368 - mae: 0.5368 - val_loss: 0.5606 - val_mae: 0.5606
Epoch 160/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5468 - mae: 0.5468 - val_loss: 0.5735 - val_mae: 0.5735
Epoch 161/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5519 - mae: 0.5519 - val_loss: 0.5594 - val_mae: 0.5594
Epoch 162/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5551 - mae: 0.5551 - val_loss: 0.5956 - val_mae: 0.5956
Epoch 163/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5449 - mae: 0.5449 - val_loss: 0.5733 - val_mae: 0.5733
Epoch 164/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5537 - mae: 0.5537 - val_loss: 0.5527 - val_mae: 0.5527
Epoch 165/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5321 - mae: 0.5321 - val_loss: 0.5645 - val_mae: 0.5645
Epoch 166/200
122/122 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5479 - mae: 0.5479 - val_loss: 0.5792 - val_mae: 0.5792
Epoch 167/200

In [10]:
# No modifique el código
results = model.evaluate(x_test, y_test, verbose=1)
print('Test Loss: {}'.format(results))

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5831 - mae: 0.5831
Test Loss: [0.5870789885520935, 0.5870789885520935]

<a name='1.2'></a>
## Cuestión 2: Utilice el mismo modelo de la cuestión anterior pero añadiendo al menos dos técnicas distinas de regularización. No es necesario reducir el test loss.

Ejemplos de regularización: [Prevent_Overfitting.ipynb](https://github.com/ezponda/intro_deep_learning/blob/main/class/Fundamentals/Prevent_Overfitting.ipynb)

In [11]:
from tensorflow.keras import layers, regularizers

In [12]:
model = tf.keras.models.Sequential()


# regularization: L2 + Dropout


n_features = x_train_scaled.shape[1]

model = tf.keras.models.Sequential([
    layers.Input(shape=(n_features,)),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.30),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.30),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.30),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),

    layers.Dense(1)
])

In [13]:
# Compilación del modelo


model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss="mae",
    metrics=["mae"]
)

In [14]:
batch_size= 128 #increase batch size to smooth gradients, and reduce steps per epoch

In [15]:
# No modifique el código
model.fit(x_train,
          y_train,
          epochs=200,
          batch_size=batch_size,
          validation_split=0.2,
          verbose=1)

Epoch 1/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 105ms/step - loss: 7.9109 - mae: 7.8903 - val_loss: 3.8098 - val_mae: 3.7899
Epoch 2/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.8524 - mae: 2.8328 - val_loss: 3.9573 - val_mae: 3.9381
Epoch 3/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.2791 - mae: 2.2600 - val_loss: 3.8237 - val_mae: 3.8049
Epoch 4/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.8466 - mae: 1.8277 - val_loss: 3.5116 - val_mae: 3.4930
Epoch 5/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6567 - mae: 1.6381 - val_loss: 3.2204 - val_mae: 3.2019
Epoch 6/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5050 - mae: 1.4866 - val_loss: 2.9747 - val_mae: 2.9564
Epoch 7/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3889 - mae: 1.3705 - val_loss: 3.0106 - val_mae: 2.9923
Epoch 8/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.3180 - mae: 1.2997 - val_loss: 3.1034 - val_mae: 3.0852
Epoch 9/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2664 - mae: 1.2482 - val_loss: 2.5890 - val_mae: 2.5709
Epoch 10/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.1905 - mae: 1.1724 - val_loss: 3.0095 - val_mae: 2.9914
Epoch 11/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.1869 - mae: 1.1688 - val_loss: 2.9073 - val_mae: 2.8893
Epoch 12/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1209 - mae: 1.1029 - val_loss: 2.6834 - val_mae: 2.6654
Epoch 13/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0498 - mae: 1.0318 - val_loss: 2.7464 - val_mae: 2.7285
Epoch 14/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0131 - mae: 0.9952 - val_loss: 2.6213 - val_mae: 2.6034
Epoch 15/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9922 - mae: 0.9744 - val_loss: 2.6102 - val_mae: 2.5924
Epoch 16/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9990 - mae: 0.9812 - val_loss: 2.3572 - val_mae: 2.3394
Epoch 17/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9913 - mae: 0.9736 - val_loss: 2.5279 - val_mae: 2.5102
Epoch 18/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9646 - mae: 0.9469 - val_loss: 2.1875 - val_mae: 2.1699
Epoch 19/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9315 - mae: 0.9139 - val_loss: 2.2444 - val_mae: 2.2268
Epoch 20/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8893 - mae: 0.8717 - val_loss: 2.4504 - val_mae: 2.4328
Epoch 21/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9129 - mae: 0.8953 - val_loss: 2.4013 - val_mae: 2.3838
Epoch 22/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8584 - mae: 0.8409 - val_loss: 2.2562 - val_mae: 2.2387
Epoch 23/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8436 - mae: 0.8261 - val_loss: 2.1888 - val_mae: 2.1714
Epoch 24/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8542 - mae: 0.8367 - val_loss: 2.0952 - val_mae: 2.0778
Epoch 25/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8305 - mae: 0.8131 - val_loss: 2.1323 - val_mae: 2.1149
Epoch 26/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8087 - mae: 0.7913 - val_loss: 2.1363 - val_mae: 2.1190
Epoch 27/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8185 - mae: 0.8011 - val_loss: 2.2398 - val_mae: 2.2225
Epoch 28/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8046 - mae: 0.7873 - val_loss: 2.0086 - val_mae: 1.9914
Epoch 29/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7932 - mae: 0.7760 - val_loss: 2.0095 - val_mae: 1.9923
Epoch 30/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7749 - mae: 0.7577 - val_loss: 2.0913 - val_mae: 2.0741
Epoch 31/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7597 - mae: 0.7426 - val_loss: 1.8483 - val_mae: 1.8311
Epoch 32/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7686 - mae: 0.7515 - val_loss: 1.8617 - val_mae: 1.8446
Epoch 33/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7568 - mae: 0.7397 - val_loss: 1.8376 - val_mae: 1.8205
Epoch 34/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7542 - mae: 0.7371 - val_loss: 1.6980 - val_mae: 1.6810
Epoch 35/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7596 - mae: 0.7425 - val_loss: 1.6822 - val_mae: 1.6652
Epoch 36/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7420 - mae: 0.7249 - val_loss: 1.7245 - val_mae: 1.7075
Epoch 37/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7284 - mae: 0.7114 - val_loss: 1.5441 - val_mae: 1.5271
Epoch 38/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7204 - mae: 0.7034 - val_loss: 1.6294 - val_mae: 1.6125
Epoch 39/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7257 - mae: 0.7088 - val_loss: 1.5672 - val_mae: 1.5503
Epoch 40/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7028 - mae: 0.6859 - val_loss: 1.4278 - val_mae: 1.4109
Epoch 41/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7253 - mae: 0.7084 - val_loss: 1.5341 - val_mae: 1.5172
Epoch 42/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7016 - mae: 0.6848 - val_loss: 1.6267 - val_mae: 1.6098
Epoch 43/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7066 - mae: 0.6897 - val_loss: 1.3177 - val_mae: 1.3009
Epoch 44/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6977 - mae: 0.6809 - val_loss: 1.4020 - val_mae: 1.3852
Epoch 45/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7024 - mae: 0.6855 - val_loss: 1.4351 - val_mae: 1.4183
Epoch 46/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6951 - mae: 0.6783 - val_loss: 1.2851 - val_mae: 1.2683
Epoch 47/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6883 - mae: 0.6716 - val_loss: 1.3271 - val_mae: 1.3103
Epoch 48/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6622 - mae: 0.6455 - val_loss: 1.2135 - val_mae: 1.1968
Epoch 49/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6907 - mae: 0.6740 - val_loss: 1.1389 - val_mae: 1.1221
Epoch 50/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6796 - mae: 0.6629 - val_loss: 1.1833 - val_mae: 1.1666
Epoch 51/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6760 - mae: 0.6593 - val_loss: 1.1916 - val_mae: 1.1749
Epoch 52/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6810 - mae: 0.6643 - val_loss: 1.2673 - val_mae: 1.2506
Epoch 53/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6874 - mae: 0.6707 - val_loss: 1.0347 - val_mae: 1.0180
Epoch 54/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6732 - mae: 0.6565 - val_loss: 1.1975 - val_mae: 1.1809
Epoch 55/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6834 - mae: 0.6668 - val_loss: 1.1220 - val_mae: 1.1054
Epoch 56/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6905 - mae: 0.6739 - val_loss: 1.0465 - val_mae: 1.0299
Epoch 57/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6729 - mae: 0.6563 - val_loss: 0.9114 - val_mae: 0.8948
Epoch 58/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6594 - mae: 0.6428 - val_loss: 1.0247 - val_mae: 1.0081
Epoch 59/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6663 - mae: 0.6497 - val_loss: 1.0948 - val_mae: 1.0782
Epoch 60/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6608 - mae: 0.6442 - val_loss: 0.9784 - val_mae: 0.9618
Epoch 61/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6640 - mae: 0.6474 - val_loss: 1.0217 - val_mae: 1.0051
Epoch 62/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6574 - mae: 0.6408 - val_loss: 1.1441 - val_mae: 1.1275
Epoch 63/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6701 - mae: 0.6535 - val_loss: 1.0392 - val_mae: 1.0226
Epoch 64/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6576 - mae: 0.6410 - val_loss: 1.0344 - val_mae: 1.0179
Epoch 65/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6471 - mae: 0.6306 - val_loss: 0.9264 - val_mae: 0.9098
Epoch 66/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6559 - mae: 0.6394 - val_loss: 0.9372 - val_mae: 0.9206
Epoch 67/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6623 - mae: 0.6457 - val_loss: 0.9057 - val_mae: 0.8891
Epoch 68/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6501 - mae: 0.6335 - val_loss: 0.9301 - val_mae: 0.9135
Epoch 69/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6562 - mae: 0.6396 - val_loss: 0.9332 - val_mae: 0.9166
Epoch 70/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6571 - mae: 0.6405 - val_loss: 0.9234 - val_mae: 0.9068
Epoch 71/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6439 - mae: 0.6273 - val_loss: 0.8958 - val_mae: 0.8793
Epoch 72/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6477 - mae: 0.6311 - val_loss: 0.9128 - val_mae: 0.8962
Epoch 73/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6554 - mae: 0.6388 - val_loss: 0.9369 - val_mae: 0.9203
Epoch 74/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6547 - mae: 0.6381 - val_loss: 0.9140 - val_mae: 0.8974
Epoch 75/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6499 - mae: 0.6333 - val_loss: 0.8990 - val_mae: 0.8823
Epoch 76/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6393 - mae: 0.6227 - val_loss: 0.9009 - val_mae: 0.8843
Epoch 77/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6452 - mae: 0.6286 - val_loss: 0.9546 - val_mae: 0.9380
Epoch 78/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6332 - mae: 0.6166 - val_loss: 0.8842 - val_mae: 0.8676
Epoch 79/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6435 - mae: 0.6269 - val_loss: 0.9483 - val_mae: 0.9317
Epoch 80/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6400 - mae: 0.6234 - val_loss: 0.8851 - val_mae: 0.8684
Epoch 81/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6287 - mae: 0.6121 - val_loss: 0.8492 - val_mae: 0.8326
Epoch 82/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6343 - mae: 0.6177 - val_loss: 0.9472 - val_mae: 0.9305
Epoch 83/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6345 - mae: 0.6179 - val_loss: 0.8699 - val_mae: 0.8532
Epoch 84/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6348 - mae: 0.6181 - val_loss: 0.8239 - val_mae: 0.8072
Epoch 85/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6470 - mae: 0.6304 - val_loss: 0.9057 - val_mae: 0.8890
Epoch 86/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6341 - mae: 0.6174 - val_loss: 0.9160 - val_mae: 0.8993
Epoch 87/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6402 - mae: 0.6235 - val_loss: 0.8605 - val_mae: 0.8438
Epoch 88/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6560 - mae: 0.6393 - val_loss: 0.9161 - val_mae: 0.8994
Epoch 89/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6396 - mae: 0.6229 - val_loss: 0.8291 - val_mae: 0.8123
Epoch 90/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6413 - mae: 0.6246 - val_loss: 0.8973 - val_mae: 0.8806
Epoch 91/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6370 - mae: 0.6203 - val_loss: 0.8219 - val_mae: 0.8051
Epoch 92/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6241 - mae: 0.6073 - val_loss: 0.8232 - val_mae: 0.8065
Epoch 93/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6337 - mae: 0.6170 - val_loss: 0.8233 - val_mae: 0.8066
Epoch 94/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6246 - mae: 0.6079 - val_loss: 0.8503 - val_mae: 0.8335
Epoch 95/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6409 - mae: 0.6241 - val_loss: 0.8789 - val_mae: 0.8622
Epoch 96/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6415 - mae: 0.6248 - val_loss: 0.8581 - val_mae: 0.8413
Epoch 97/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6291 - mae: 0.6124 - val_loss: 0.8592 - val_mae: 0.8425
Epoch 98/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6182 - mae: 0.6015 - val_loss: 0.8141 - val_mae: 0.7974
Epoch 99/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6459 - mae: 0.6292 - val_loss: 0.8309 - val_mae: 0.8142
Epoch 100/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6260 - mae: 0.6093 - val_loss: 0.8175 - val_mae: 0.8008
Epoch 101/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6342 - mae: 0.6175 - val_loss: 0.8552 - val_mae: 0.8384
Epoch 102/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6267 - mae: 0.6100 - val_loss: 0.7952 - val_mae: 0.7785
Epoch 103/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6325 - mae: 0.6158 - val_loss: 0.8630 - val_mae: 0.8462
Epoch 104/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6286 - mae: 0.6119 - val_loss: 0.8418 - val_mae: 0.8251
Epoch 105/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6147 - mae: 0.5979 - val_loss: 0.7863 - val_mae: 0.7696
Epoch 106/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6226 - mae: 0.6058 - val_loss: 0.8080 - val_mae: 0.7912
Epoch 107/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6216 - mae: 0.6048 - val_loss: 0.7777 - val_mae: 0.7609
Epoch 108/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6202 - mae: 0.6034 - val_loss: 0.7906 - val_mae: 0.7738
Epoch 109/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6139 - mae: 0.5971 - val_loss: 0.8589 - val_mae: 0.8421
Epoch 110/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6280 - mae: 0.6112 - val_loss: 0.8167 - val_mae: 0.7999
Epoch 111/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6211 - mae: 0.6043 - val_loss: 0.8280 - val_mae: 0.8112
Epoch 112/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6224 - mae: 0.6056 - val_loss: 0.8721 - val_mae: 0.8553
Epoch 113/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6157 - mae: 0.5989 - val_loss: 0.7992 - val_mae: 0.7824
Epoch 114/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6231 - mae: 0.6063 - val_loss: 0.8753 - val_mae: 0.8585
Epoch 115/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6212 - mae: 0.6044 - val_loss: 0.7978 - val_mae: 0.7810
Epoch 116/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6273 - mae: 0.6105 - val_loss: 0.7620 - val_mae: 0.7452
Epoch 117/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6125 - mae: 0.5957 - val_loss: 0.7946 - val_mae: 0.7778
Epoch 118/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6123 - mae: 0.5955 - val_loss: 0.7766 - val_mae: 0.7599
Epoch 119/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6214 - mae: 0.6046 - val_loss: 0.8058 - val_mae: 0.7891
Epoch 120/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6211 - mae: 0.6043 - val_loss: 0.7975 - val_mae: 0.7807
Epoch 121/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6119 - mae: 0.5951 - val_loss: 0.8061 - val_mae: 0.7893
Epoch 122/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6114 - mae: 0.5946 - val_loss: 0.8266 - val_mae: 0.8098
Epoch 123/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6178 - mae: 0.6010 - val_loss: 0.8520 - val_mae: 0.8353
Epoch 124/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6348 - mae: 0.6181 - val_loss: 0.8118 - val_mae: 0.7951
Epoch 125/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6265 - mae: 0.6098 - val_loss: 0.8022 - val_mae: 0.7855
Epoch 126/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6070 - mae: 0.5903 - val_loss: 0.7927 - val_mae: 0.7760
Epoch 127/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6244 - mae: 0.6077 - val_loss: 0.8026 - val_mae: 0.7859
Epoch 128/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6218 - mae: 0.6051 - val_loss: 0.8026 - val_mae: 0.7859
Epoch 129/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6174 - mae: 0.6007 - val_loss: 0.7921 - val_mae: 0.7754
Epoch 130/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6056 - mae: 0.5889 - val_loss: 0.7535 - val_mae: 0.7368
Epoch 131/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5969 - mae: 0.5802 - val_loss: 0.7866 - val_mae: 0.7699
Epoch 132/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6233 - mae: 0.6066 - val_loss: 0.7167 - val_mae: 0.7000
Epoch 133/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6233 - mae: 0.6066 - val_loss: 0.7849 - val_mae: 0.7682
Epoch 134/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6057 - mae: 0.5890 - val_loss: 0.7327 - val_mae: 0.7160
Epoch 135/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6244 - mae: 0.6077 - val_loss: 0.8106 - val_mae: 0.7939
Epoch 136/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6183 - mae: 0.6017 - val_loss: 0.8019 - val_mae: 0.7853
Epoch 137/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6153 - mae: 0.5987 - val_loss: 0.7328 - val_mae: 0.7162
Epoch 138/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6163 - mae: 0.5997 - val_loss: 0.7200 - val_mae: 0.7034
Epoch 139/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6045 - mae: 0.5879 - val_loss: 0.7526 - val_mae: 0.7360
Epoch 140/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6170 - mae: 0.6004 - val_loss: 0.7437 - val_mae: 0.7271
Epoch 141/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6127 - mae: 0.5961 - val_loss: 0.7465 - val_mae: 0.7299
Epoch 142/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6086 - mae: 0.5921 - val_loss: 0.7068 - val_mae: 0.6903
Epoch 143/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6044 - mae: 0.5878 - val_loss: 0.7413 - val_mae: 0.7247
Epoch 144/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6064 - mae: 0.5898 - val_loss: 0.7363 - val_mae: 0.7198
Epoch 145/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5985 - mae: 0.5819 - val_loss: 0.7341 - val_mae: 0.7176
Epoch 146/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6170 - mae: 0.6004 - val_loss: 0.7073 - val_mae: 0.6908
Epoch 147/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6019 - mae: 0.5854 - val_loss: 0.7442 - val_mae: 0.7277
Epoch 148/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5842 - mae: 0.5677 - val_loss: 0.7271 - val_mae: 0.7106
Epoch 149/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6072 - mae: 0.5907 - val_loss: 0.7191 - val_mae: 0.7026
Epoch 150/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5961 - mae: 0.5796 - val_loss: 0.7032 - val_mae: 0.6868
Epoch 151/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5982 - mae: 0.5818 - val_loss: 0.7268 - val_mae: 0.7104
Epoch 152/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5847 - mae: 0.5683 - val_loss: 0.6929 - val_mae: 0.6765
Epoch 153/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6020 - mae: 0.5856 - val_loss: 0.7249 - val_mae: 0.7085
Epoch 154/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5993 - mae: 0.5829 - val_loss: 0.6837 - val_mae: 0.6674
Epoch 155/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5901 - mae: 0.5737 - val_loss: 0.6778 - val_mae: 0.6615
Epoch 156/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5952 - mae: 0.5788 - val_loss: 0.6626 - val_mae: 0.6463
Epoch 157/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5988 - mae: 0.5825 - val_loss: 0.7185 - val_mae: 0.7022
Epoch 158/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5919 - mae: 0.5755 - val_loss: 0.6807 - val_mae: 0.6643
Epoch 159/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5893 - mae: 0.5730 - val_loss: 0.6902 - val_mae: 0.6739
Epoch 160/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5805 - mae: 0.5642 - val_loss: 0.6532 - val_mae: 0.6369
Epoch 161/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5974 - mae: 0.5811 - val_loss: 0.6349 - val_mae: 0.6186
Epoch 162/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5863 - mae: 0.5700 - val_loss: 0.6219 - val_mae: 0.6056
Epoch 163/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5812 - mae: 0.5649 - val_loss: 0.6237 - val_mae: 0.6075
Epoch 164/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5776 - mae: 0.5614 - val_loss: 0.6494 - val_mae: 0.6332
Epoch 165/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5664 - mae: 0.5503 - val_loss: 0.6204 - val_mae: 0.6042
Epoch 166/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5920 - mae: 0.5759 - val_loss: 0.6439 - val_mae: 0.6277
Epoch 167/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5759 - mae: 0.5597 - val_loss: 0.6526 - val_mae: 0.6365
Epoch 168/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5692 - mae: 0.5530 - val_loss: 0.6311 - val_mae: 0.6150
Epoch 169/200

In [16]:
# No modifique el código
results = model.evaluate(x_test, y_test, verbose=1)
print('Test Loss: {}'.format(results))

51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.5750 - mae: 0.5599
Test Loss: [0.5815224051475525, 0.5664090514183044]

<a name='1.3'></a>
## Cuestión 3: Utilice el mismo modelo de la cuestión anterior pero añadiendo un callback de early stopping. No es necesario reducir el test loss.

In [17]:
model = tf.keras.models.Sequential()
# regularization: L2 + Dropout


n_features = x_train_scaled.shape[1]

model = tf.keras.models.Sequential([
    layers.Input(shape=(n_features,)),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.30),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.30),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.30),

    layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(1e-4)),

    layers.Dense(1)
])

In [18]:
# Compilación del modelo


model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss="mae",
    metrics=["mae"]
)

In [23]:
## definir el early stopping callback

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=20,
    min_delta=1e-4,
    restore_best_weights=True
)

model.fit(x_train,
          y_train,
          epochs=200,
          batch_size=128,
          validation_split=0.2,
          verbose=1,
          callbacks=[early_stopping])

Epoch 1/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - loss: 0.5402 - mae: 0.5320 - val_loss: 0.5515 - val_mae: 0.5433
Epoch 2/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5339 - mae: 0.5257 - val_loss: 0.5470 - val_mae: 0.5389
Epoch 3/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5446 - mae: 0.5365 - val_loss: 0.5463 - val_mae: 0.5382
Epoch 4/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5648 - mae: 0.5567 - val_loss: 0.5511 - val_mae: 0.5430
Epoch 5/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5420 - mae: 0.5339 - val_loss: 0.5380 - val_mae: 0.5299
Epoch 6/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5362 - mae: 0.5280 - val_loss: 0.5402 - val_mae: 0.5321
Epoch 7/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5506 - mae: 0.5424 - val_loss: 0.5619 - val_mae: 0.5538
Epoch 8/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5365 - mae: 0.5284 - val_loss: 0.5479 - val_mae: 0.5398
Epoch 9/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5552 - mae: 0.5471 - val_loss: 0.5528 - val_mae: 0.5447
Epoch 10/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5533 - mae: 0.5452 - val_loss: 0.5435 - val_mae: 0.5355
Epoch 11/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5344 - mae: 0.5264 - val_loss: 0.5465 - val_mae: 0.5384
Epoch 12/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5479 - mae: 0.5399 - val_loss: 0.5456 - val_mae: 0.5375
Epoch 13/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5458 - mae: 0.5377 - val_loss: 0.5378 - val_mae: 0.5298
Epoch 14/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5365 - mae: 0.5284 - val_loss: 0.5477 - val_mae: 0.5396
Epoch 15/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5487 - mae: 0.5407 - val_loss: 0.5408 - val_mae: 0.5328
Epoch 16/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5695 - mae: 0.5615 - val_loss: 0.5598 - val_mae: 0.5517
Epoch 17/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5468 - mae: 0.5388 - val_loss: 0.5574 - val_mae: 0.5494
Epoch 18/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5558 - mae: 0.5478 - val_loss: 0.5427 - val_mae: 0.5347
Epoch 19/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5541 - mae: 0.5461 - val_loss: 0.5658 - val_mae: 0.5578
Epoch 20/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5436 - mae: 0.5356 - val_loss: 0.5507 - val_mae: 0.5426
Epoch 21/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5311 - mae: 0.5231 - val_loss: 0.5625 - val_mae: 0.5544
Epoch 22/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5498 - mae: 0.5418 - val_loss: 0.5405 - val_mae: 0.5325
Epoch 23/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5494 - mae: 0.5413 - val_loss: 0.5461 - val_mae: 0.5380
Epoch 24/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5467 - mae: 0.5387 - val_loss: 0.5769 - val_mae: 0.5689
Epoch 25/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5721 - mae: 0.5641 - val_loss: 0.5529 - val_mae: 0.5449
Epoch 26/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5483 - mae: 0.5403 - val_loss: 0.5491 - val_mae: 0.5411
Epoch 27/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5548 - mae: 0.5468 - val_loss: 0.5452 - val_mae: 0.5372
Epoch 28/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5427 - mae: 0.5346 - val_loss: 0.5666 - val_mae: 0.5586
Epoch 29/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5573 - mae: 0.5493 - val_loss: 0.5426 - val_mae: 0.5346
Epoch 30/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5539 - mae: 0.5458 - val_loss: 0.5572 - val_mae: 0.5491
Epoch 31/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5481 - mae: 0.5401 - val_loss: 0.5602 - val_mae: 0.5522
Epoch 32/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5575 - mae: 0.5495 - val_loss: 0.5586 - val_mae: 0.5506
Epoch 33/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5674 - mae: 0.5594 - val_loss: 0.5429 - val_mae: 0.5349

In [24]:
# No modifique el código
results = model.evaluate(x_test, y_test, verbose=1)
print('Test Loss: {}'.format(results))

51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5546 - mae: 0.5465
Test Loss: [0.5622188448905945, 0.5541852712631226]

<a name='1.4'></a>
## Cuestión 4: ¿Podría haberse usado otra función de activación de la neurona de salida? En caso afirmativo especifíquela.

Sí, pero solo si queremos imponer restricciones al rango.

En este caso, al ser regresión, la salida correcta es lineal (sin activación).



Alternativas válidas según el caso:

[3, 9] acotado: reescalar el objetivo y usar una activación acotada.
ej.: sigmoid(con target value en [0,1]) con y_scaled=(y-3)/6, 0 tanh(con target value en [-1,1]) con y_scaled = (y-6)/3


Si no se requieren estas restricciones, me parace mantener salida lineal es lo más adecuado; usar sigmoid/tanh sin reescalar puede introducir sesgo y saturación del gradiente.

<a name='1.5'></a>
## Cuestión 5:  ¿Qué es lo que una neurona calcula?

**a)** Una función de activación seguida de una suma ponderada  de las entradas.

**b)** Una suma ponderada  de las entradas seguida de una función de activación.

**c)** Una función de pérdida, definida sobre el target.

**d)** Ninguna  de las anteriores es correcta

b)

<a name='1.6'></a>
## Cuestión 6:  ¿Cuál de estas funciones de activación no debería usarse en una capa oculta (hidden layer)?

**a)** `sigmoid`

**b)** `tanh`

**c)** `relu`

**d)** `linear`

d)

<a name='1.7'></a>
## Cuestión 7:  ¿Cuál de estas técnicas es efectiva para combatir el overfitting en una red con varias capas ocultas? Ponga todas las que lo sean.

**a)** Dropout

**b)** Regularización L2.

**c)** Aumentar el tamaño del test set.

**d)** Aumentar el tamaño del validation set.

**e)** Reducir el número de capas de la red.

**f)** Data augmentation.

a) b) e) f)

<a name='1.8'></a>
## Cuestión 8:  Supongamos que queremos entrenar una red para un problema de clasificación de imágenes con las siguientes clases: {'perro','gato','persona'}. ¿Cuántas neuronas y que función de activación debería tener la capa de salida? ¿Qué función de pérdida (loss function) debería usarse?

Número neuronas en la salida: 3 (una por clase: perro, gato, persona).

Activación: softmax (clases mutuamente excluyentes - distribución de probabilidad que suma 1).

Pérdida (loss function):

Si las etiquetas están one-hot -> categorical_crossentropy.

Si las etiquetas son enteros 0/1/2 -> sparse_categorical_crossentropy.

(Métrica típica: accuracy.)